spring.application.name=doctor-appointment
#for mongodb
spring.data.mongodb.uri=mongodb://localhost:27017/doctorAppointmentDB
#mongock.runner-type=initializingbean
mongock.enabled=true
mongock.migration-scan-package=com.tania.doctor_appointment.migration
logging.file.name=logs/app.log
logging.level.io.mongock=DEBUG
#for logs
#logging:
#    level:
#        root: INFO
#        org.springframework: INFO
#        com.tania: DEBUG
#
#    file:
#        name: logs/doctor-app.log
